server:
  port: 8082

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/curve_customizing?useUnicode=true&amp&characterEncoding=utf8
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      username: root
      password: 123456

  jpa:
    hibernate:
      ddl-auto: update
      dialect:MySQL5InnoDBDialect:
      database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true




#showSql
logging:
  level:
    com:
      example:
        mapper : debug