fx-sdn-adapter:
  common:
    start_project_name: fe_curve
    start_service_name: irs-custom-curve
    start_app_class_name: com.sumscope.fe.curvecustomizing.CurvecustomizingApplication
    service_log_dir: /opt/sumscope/fx_salt/log/irs-custom-curve
    service_data_dir: /opt/sumscope/fx_salt/data/irs-custom-curve
    start_jvm_ms: 512M
    start_jvm_mx: 2G

  envs:
    DEV:
      application_lava_zk: 172.16.97.115:2181,172.16.97.116:2181,172.16.97.139:2181
      application_lava_server_host: 172.16.97.195
      application_lava_server_port: 5001
      application_lava_server_key: SERVER.LAVA.SDN_FX_ADAPTER
      server_port: 8310
      server_servlet_context_path: /adapter
      spring_rabbitmq_host: 172.16.87.69
      spring_redis_cluster_nodes: redis.dev.sumscope.com:6379
    QA:
      application_lava_zk: 172.16.97.111:2181,172.16.97.114:2181,172.16.97.145:2181
      application_lava_server_host: 172.16.96.67
      application_lava_server_port: 5001
      application_lava_server_key: SERVER.LAVA.SDN_FX_ADAPTER
      server_port: 8310
      server_servlet_context_path: /adapter
      spring_rabbitmq_host: rabbitmq-cdh.qa.sumscope.com
      spring_redis_cluster_nodes: redis.qa.sumscope.com:6379
    PRD:
      application_lava_zk: sdn-zk1.prd.sumscope.com:2181,sdn-zk2.prd.sumscope.com:2181,sdn-zk3.prd.sumscope.com:2181
      application_lava_server_host: 172.18.11.61
      application_lava_server_port: 5001
      application_lava_server_key: SERVER.LAVA.SDN_FX_ADAPTER
      server_port: 8310
      server_servlet_context_path: /adapter
      spring_rabbitmq_host: rabbitmq-cdh.prd.sumscope.com
      spring_redis_cluster_nodes: redis-cdh.prd.sumscope.com:6379